# Generated by Django 5.1.1 on 2024-10-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
    ]
