# Generated by Django 5.1.1 on 2024-10-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_request_inventoryaccessrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaccessrequest',
            name='status',
            field=models.CharField(choices=[('inventory_pending', 'Waiting for Inventory Approval'), ('inventory_approved', 'Inventory Approved'), ('inventory_declined', 'Inventory Declined')], default='inventory_pending', max_length=20),
        ),
    ]
