# Generated by Django 5.1.2 on 2024-10-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requested_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
