# Generated by Django 5.1.1 on 2024-10-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AddField(
            model_name='reply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='replies/'),
        ),
    ]
