# Generated by Django 5.1.2 on 2024-10-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditmemorequest',
            name='new_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
