# Generated by Django 5.1.1 on 2024-10-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_profile',
            new_name='user',
        ),
    ]
