# Generated by Django 5.1.1 on 2024-10-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_message_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
